### ISSUE TITLE
The version for MATLAB 2020a is showing errors in the simulation

### ISSUE THREAD

**Issue by s18el05** [MustafaSaraoglu/AutonomousVehicleModeling#20]
Hello,

Thank you for the quick response on the previous issue, I tried the new file for ManeuverPlanning.slx.2020a and I receive this list of errors.
Can you please support?
![image](https://user-images.githubusercontent.com/97359621/200526548-1419546b-818d-4e96-8a5e-202d4bea8162.png)

Thank you! :)

**Comment by MustafaSaraoglu** [comment]
Hello, I think you may have forgotten to rename the model to "ManeuverPlanning", as I mentioned in my last comment because your error message shows the directory as "ManeuverPlanning_2020a/Other_Vehicles". All the scripts are programmed to use the logged signals from the Simulink model as "ManeuverPlanning". When I tried it by renaming and deleting the previous r2020b version of the .slx file, it worked without errors. 

1- However, if you still get the same error, do you see the plot where vehicles move, or does this error occur right at the beginning?

2- Can you also let me know which scripts or commands did you run to get this error?

**Comment by s18el05** [comment]
Hello,

Thank you for the support!
I changed the name of the file but still receive the same error.
1. No, I can't see the plots the error occurs at the beginning of the simulation
2. I just tried to run the simulation of the whole Simulink model,  but the simulation works when I run the script "DrivingScenarios.m" I assume this is the way to use it isn't it?

**Comment by MustafaSaraoglu** [comment]
Yes, because it needs the initial values from the script. The Simulink model should not be run alone. This folder "Maneuver Planning" has more complex models and the initial values/configurations are input by scripts, therefore, you shouldn't run the Simulink model directly. Do you see the plots when you run "DrivingScenarios.m" script (you can also run it section by section)?
